name: run 

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'

    - run: javac src/おぶじぇくとあうとぷっとすとりーむをつかったしりあらいず.java

    - run: java src/おぶじぇくとあうとぷっとすとりーむをつかったしりあらいず.java